name: Regression Testing

on: [push]
  # schedule:
    # - cron: 0 0 * * *

jobs:
  test:
    # Regression tests only run on Linux because:
    # - GitHub Actions only supports Windows-based Docker containers on Windows:
    #   https://github.com/actions/virtual-environments/issues/1143
    # - GitHub Actions doesn't support Docker on macOS:
    #   https://github.community/t/is-it-possible-to-install-and-configure-docker-on-macos-runner/16981/7
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        # python-version: [ "3.6", "3.7", "3.8", "3.9" ]
        python-version: [ "3.6" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -s -rs
        env:
          QC_USER_ID: ${{ secrets.QC_USER_ID }}
          QC_API_TOKEN: ${{ secrets.QC_API_TOKEN }}
