name: Regression Testing

on: [push]
  # schedule:
    # - cron: 0 0 * * *

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 1
      matrix:
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        os: [ ubuntu-latest ]
        # python-version: [ "3.6", "3.7", "3.8", "3.9" ]
        python-version: [ "3.6" ]
        include:
          - os: ubuntu-latest
            script: tests/regressions/unix.sh
          - os: macos-latest
            script: tests/regressions/unix.sh
          - os: windows-latest
            script: tests/regressions/windows.ps1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

#      - name: Run normal tests
#        run: pytest -rs
#        env:
#          QC_USER_ID: ${{ secrets.QC_USER_ID }}
#          QC_API_TOKEN: ${{ secrets.QC_API_TOKEN }}

      - name: Run regression tests
        run: ${{ matrix.script }}
        env:
          QC_USER_ID: ${{ secrets.QC_USER_ID }}
          QC_API_TOKEN: ${{ secrets.QC_API_TOKEN }}
