name: Regression Testing

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -rs
        env:
          QC_USER_ID: ${{ secrets.QC_USER_ID }}
          QC_API_TOKEN: ${{ secrets.QC_API_TOKEN }}
